// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9vkK2DTzgsibw1mE6bpxb7GkgMabxe8',
    appId: '1:737747079267:web:d44cc7f5406477b106a856',
    messagingSenderId: '737747079267',
    projectId: 'flutter-firebase-56ccd',
    authDomain: 'flutter-firebase-56ccd.firebaseapp.com',
    storageBucket: 'flutter-firebase-56ccd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1y392WXTz5TaJSvOt2nPSGfykB2OvibY',
    appId: '1:737747079267:android:6d1843fa3c1088ab06a856',
    messagingSenderId: '737747079267',
    projectId: 'flutter-firebase-56ccd',
    storageBucket: 'flutter-firebase-56ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60-omBp8yydvJaO5JxdXZBkZgERS3yhY',
    appId: '1:737747079267:ios:ed97f72911291bee06a856',
    messagingSenderId: '737747079267',
    projectId: 'flutter-firebase-56ccd',
    storageBucket: 'flutter-firebase-56ccd.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60-omBp8yydvJaO5JxdXZBkZgERS3yhY',
    appId: '1:737747079267:ios:be09a80b41f41b2a06a856',
    messagingSenderId: '737747079267',
    projectId: 'flutter-firebase-56ccd',
    storageBucket: 'flutter-firebase-56ccd.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
